import { createCipheriv, createDecipheriv, createHash, randomBytes } from "node:crypto";
import { Router } from "express";
import { asyncHandler } from "../../common/async-handler";
import { HttpError } from "../../common/http-error";
import { required } from "../../common/validation";
import { prisma } from "../../database/prisma";

export const clinicalNotesRoutes = Router();
const key = () => { const secret = process.env.CLINICAL_NOTES_ENCRYPTION_KEY; if (!secret) throw new HttpError(500, "ENCRYPTION_NOT_CONFIGURED", "Criptografia de notas não configurada."); return createHash("sha256").update(secret).digest(); };
function encrypt(content: string) { const iv = randomBytes(12), cipher = createCipheriv("aes-256-gcm", key(), iv); const encrypted = Buffer.concat([cipher.update(content, "utf8"), cipher.final()]); return [iv, cipher.getAuthTag(), encrypted].map((v) => v.toString("base64")).join("."); }
function decrypt(payload: string) { const [iv, tag, encrypted] = payload.split(".").map((v) => Buffer.from(v, "base64")); const decipher = createDecipheriv("aes-256-gcm", key(), iv); decipher.setAuthTag(tag); return Buffer.concat([decipher.update(encrypted), decipher.final()]).toString("utf8"); }
async function ownedSession(id: string, ownerUserId: string) { const session = await prisma.session.findFirst({ where: { id, ownerUserId } }); if (!session) throw new HttpError(404, "SESSION_NOT_FOUND", "Sessão não encontrada."); return session; }

clinicalNotesRoutes.get("/sessions/:sessionId/notes", asyncHandler(async (request, response) => { const ownerUserId = response.locals.user.id; await ownedSession(request.params.sessionId, ownerUserId); const notes = await prisma.clinicalNote.findMany({ where: { sessionId: request.params.sessionId, ownerUserId }, orderBy: { createdAt: "desc" } }); await prisma.auditLog.create({ data: { ownerUserId, actorUserId: ownerUserId, entityType: "clinical_note", action: "read", metadata: { sessionId: request.params.sessionId } } }); response.json({ data: notes.map((n) => ({ id: n.id, sessionId: n.sessionId, content: decrypt(n.encryptedContent), createdAt: n.createdAt, updatedAt: n.updatedAt })) }); }));
clinicalNotesRoutes.post("/sessions/:sessionId/notes", asyncHandler(async (request, response) => { required(request.body, ["content"]); const ownerUserId = response.locals.user.id; await ownedSession(request.params.sessionId, ownerUserId); const note = await prisma.$transaction(async (tx) => { const created = await tx.clinicalNote.create({ data: { ownerUserId, sessionId: request.params.sessionId, encryptedContent: encrypt(String(request.body.content)) } }); await tx.auditLog.create({ data: { ownerUserId, actorUserId: ownerUserId, entityType: "clinical_note", entityId: created.id, action: "create" } }); return created; }); response.status(201).json({ data: { id: note.id, sessionId: note.sessionId, content: request.body.content, createdAt: note.createdAt } }); }));
clinicalNotesRoutes.patch("/notes/:id", asyncHandler(async (request, response) => { required(request.body, ["content"]); const ownerUserId = response.locals.user.id; const current = await prisma.clinicalNote.findFirst({ where: { id: request.params.id, ownerUserId } }); if (!current) throw new HttpError(404, "NOTE_NOT_FOUND", "Nota não encontrada."); const data = await prisma.clinicalNote.update({ where: { id: current.id }, data: { encryptedContent: encrypt(String(request.body.content)) } }); await prisma.auditLog.create({ data: { ownerUserId, actorUserId: ownerUserId, entityType: "clinical_note", entityId: data.id, action: "update" } }); response.json({ data: { id: data.id, content: request.body.content, updatedAt: data.updatedAt } }); }));
clinicalNotesRoutes.delete("/notes/:id", asyncHandler(async (request, response) => { const ownerUserId = response.locals.user.id; const current = await prisma.clinicalNote.findFirst({ where: { id: request.params.id, ownerUserId } }); if (!current) throw new HttpError(404, "NOTE_NOT_FOUND", "Nota não encontrada."); await prisma.$transaction([prisma.clinicalNote.delete({ where: { id: current.id } }), prisma.auditLog.create({ data: { ownerUserId, actorUserId: ownerUserId, entityType: "clinical_note", entityId: current.id, action: "delete" } })]); response.status(204).send(); }));
