import { Router } from "express";
import { asyncHandler } from "../../common/async-handler";
import { HttpError } from "../../common/http-error";
import { asDate, listResponse, pagination, required } from "../../common/validation";
import { prisma } from "../../database/prisma";

export const paymentsRoutes = Router();
const map = (item: any) => ({ ...item, amount: item.amount.toFixed(2) });
paymentsRoutes.get("/payments", asyncHandler(async (request, response) => { const { page, limit, skip } = pagination(request.query); const where = { ownerUserId: response.locals.user.id, ...(request.query.status ? { status: String(request.query.status) } : {}) }; const [items, total] = await prisma.$transaction([prisma.payment.findMany({ where, skip, take: limit, orderBy: { createdAt: "desc" } }), prisma.payment.count({ where })]); response.json(listResponse(items.map(map), page, limit, total)); }));
paymentsRoutes.get("/sessions/:sessionId/payments", asyncHandler(async (request, response) => { const data = await prisma.payment.findMany({ where: { sessionId: request.params.sessionId, ownerUserId: response.locals.user.id }, orderBy: { createdAt: "desc" } }); response.json({ data: data.map(map) }); }));
paymentsRoutes.get("/payments/:id", asyncHandler(async (request, response) => { const data = await prisma.payment.findFirst({ where: { id: request.params.id, ownerUserId: response.locals.user.id } }); if (!data) throw new HttpError(404, "PAYMENT_NOT_FOUND", "Pagamento não encontrado."); response.json({ data: map(data) }); }));
paymentsRoutes.post("/payments", asyncHandler(async (request, response) => { required(request.body, ["sessionId", "amount"]); const ownerUserId = response.locals.user.id; const amount = String(request.body.amount); if (!/^\d+(\.\d{1,2})?$/.test(amount)) throw new HttpError(400, "INVALID_AMOUNT", "amount deve ser decimal positivo com até duas casas."); const session = await prisma.session.findFirst({ where: { id: String(request.body.sessionId), ownerUserId } }); if (!session) throw new HttpError(404, "SESSION_NOT_FOUND", "Sessão não encontrada."); const data = await prisma.payment.create({ data: { ownerUserId, sessionId: session.id, amount, status: String(request.body.status ?? "pending"), dueAt: request.body.dueAt ? asDate(request.body.dueAt, "dueAt") : undefined, paidAt: request.body.paidAt ? asDate(request.body.paidAt, "paidAt") : undefined, paymentMethod: request.body.paymentMethod } }); response.status(201).json({ data: map(data) }); }));
paymentsRoutes.patch("/payments/:id", asyncHandler(async (request, response) => { const current = await prisma.payment.findFirst({ where: { id: request.params.id, ownerUserId: response.locals.user.id } }); if (!current) throw new HttpError(404, "PAYMENT_NOT_FOUND", "Pagamento não encontrado."); const data = await prisma.payment.update({ where: { id: current.id }, data: { amount: request.body.amount, status: request.body.status, dueAt: request.body.dueAt ? asDate(request.body.dueAt, "dueAt") : request.body.dueAt, paidAt: request.body.paidAt ? asDate(request.body.paidAt, "paidAt") : request.body.paidAt, paymentMethod: request.body.paymentMethod } }); response.json({ data: map(data) }); }));
