begin;

create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.users (
  id uuid primary key default gen_random_uuid(),
  name text not null check (btrim(name) <> ''),
  email text not null,
  password_hash text not null,
  plane text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists users_email_unique_idx
  on public.users (lower(email));

create table if not exists public.patients (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users(id) on delete cascade,
  nome text not null check (btrim(nome) <> ''),
  telefone text not null,
  email text not null,
  status text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  is_active boolean not null default true
);

create table if not exists public.patient_details (
  id uuid primary key default gen_random_uuid(),
  patient_id uuid not null unique references public.patients(id) on delete cascade,
  cpf text,
  date_of_birth date,
  gender text,
  cep text,
  city text,
  neighborhood text,
  state_of_country text,
  address text,
  number text,
  complement text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  is_active boolean not null default true
);

create table if not exists public.appointments (
  id uuid primary key default gen_random_uuid(),
  patient_id uuid not null references public.patients(id) on delete cascade,
  patient_name text not null,
  date_time timestamptz not null,
  description text not null,
  is_confirmed boolean not null default false,
  avatar_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.schedule_calendar (
  id uuid primary key default gen_random_uuid(),
  appointment_id uuid not null unique references public.appointments(id) on delete cascade,
  date date not null,
  start_hour time not null,
  end_hour time not null,
  status text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint schedule_calendar_valid_hours check (end_hour > start_hour)
);

create table if not exists public.patient_history (
  id uuid primary key default gen_random_uuid(),
  patient_id uuid not null references public.patients(id) on delete cascade,
  title text not null,
  description text not null,
  professional text not null,
  date timestamptz not null,
  status text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.sessions (
  id bigint generated by default as identity primary key,
  patient_id uuid not null references public.patients(id) on delete cascade,
  date_time timestamptz,
  status text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.clinical_notes (
  id bigint generated by default as identity primary key,
  session_id bigint not null unique references public.sessions(id) on delete cascade,
  conteudo_criptografado text not null,
  criado_em timestamptz not null default now()
);

create table if not exists public.payments (
  id bigint generated by default as identity primary key,
  session_id bigint not null references public.sessions(id) on delete cascade,
  valor numeric(12, 2) not null check (valor >= 0),
  status text not null,
  data_pagamento timestamptz not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.consultations (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users(id) on delete cascade,
  title text not null,
  doctor text not null,
  location text not null,
  date timestamptz not null,
  status text not null,
  diagnosis text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.activity_patient (
  id uuid primary key default gen_random_uuid(),
  patient_id uuid not null references public.patients(id) on delete cascade,
  date_time timestamptz not null,
  patient_name text not null,
  description text not null,
  is_confirmed boolean not null default true,
  avatar_url text
);

create table if not exists public.gender_options (
  id smallint generated by default as identity primary key,
  label text not null,
  value text not null unique,
  is_active boolean not null default true
);

create table if not exists public.status_reference (
  id smallint generated by default as identity primary key,
  domain text not null,
  code text not null,
  label text not null,
  is_active boolean not null default true,
  constraint status_reference_domain_code_unique unique (domain, code)
);

create index if not exists patients_user_id_idx on public.patients(user_id);
create index if not exists appointments_patient_id_idx on public.appointments(patient_id);
create index if not exists appointments_date_time_idx on public.appointments(date_time);
create index if not exists schedule_calendar_date_idx on public.schedule_calendar(date);
create index if not exists patient_history_patient_id_idx on public.patient_history(patient_id);
create index if not exists patient_history_date_idx on public.patient_history(date);
create index if not exists sessions_patient_id_idx on public.sessions(patient_id);
create index if not exists sessions_date_time_idx on public.sessions(date_time);
create index if not exists payments_session_id_idx on public.payments(session_id);
create index if not exists payments_data_pagamento_idx on public.payments(data_pagamento);
create index if not exists consultations_user_id_idx on public.consultations(user_id);
create index if not exists consultations_date_idx on public.consultations(date);
create index if not exists activity_patient_patient_id_idx on public.activity_patient(patient_id);
create index if not exists activity_patient_date_time_idx on public.activity_patient(date_time desc);

do $$
declare
  table_name text;
begin
  foreach table_name in array array[
    'users', 'patients', 'patient_details', 'appointments',
    'schedule_calendar', 'patient_history', 'sessions', 'payments',
    'consultations'
  ]
  loop
    execute format('drop trigger if exists %I on public.%I', 'set_' || table_name || '_updated_at', table_name);
    execute format(
      'create trigger %I before update on public.%I for each row execute function public.set_updated_at()',
      'set_' || table_name || '_updated_at',
      table_name
    );
  end loop;
end;
$$;

insert into public.gender_options (label, value)
values
  ('Feminino', 'female'),
  ('Masculino', 'male'),
  ('Não binário', 'non_binary'),
  ('Prefiro não informar', 'not_informed')
on conflict (value) do nothing;

alter table public.users enable row level security;
alter table public.patients enable row level security;
alter table public.patient_details enable row level security;
alter table public.appointments enable row level security;
alter table public.schedule_calendar enable row level security;
alter table public.patient_history enable row level security;
alter table public.sessions enable row level security;
alter table public.clinical_notes enable row level security;
alter table public.payments enable row level security;
alter table public.consultations enable row level security;
alter table public.activity_patient enable row level security;
alter table public.gender_options enable row level security;
alter table public.status_reference enable row level security;

commit;
